### ISSUE TITLE
deployments management

### ISSUE THREAD

**Issue by jessie00chen** [trussworks/terraform-aws-ecs-service#105]
Hello,

This might not be a good place to ask this, but I am curious about the code block around lifecycle ignore_changes and what's the philosophy around managing the container definitions in a deployment tool and any pointer for a deployment tool that you can share.

https://github.com/trussworks/terraform-aws-ecs-service/blob/master/main.tf#L433

```
lifecycle {
    ignore_changes = [
      requires_compatibilities,
      cpu,
      memory,
      execution_role_arn,
      container_definitions,
    ]
  }
```

**Comment by brainsik** [comment]
Hi, Jessie. The short version is (in our opinion) Terraform is not a good deployment tool for these definitions. If we could, we wouldn't define them at all in Terraform. Unfortunately, AWS requires you pass in a task definition when creating an ECS service. So, we have to create what is basically a dummy task def and have Terraform ignore changes.

Currently, all the tooling we use for deploying new definitions are custom to our projects. That said, we're actively working on a unified way of doing it across projects and would likely publish the TF modules and tooling code to support it. That's some ways off right now.

**Comment by jessie00chen** [comment]
Thanks @brainsik for your quick reply! 😄

**Comment by mjmayer** [comment]
@brainsik I'm sure commenting on closed github issues is faux pas, but I'm struggling here as the single devops guy on my team. Hopefully, you can provide some feedback to keep on the right road.

I've been deploying ECS containers with Ansible, but the AWS Ansible modules have fallen too far behind and aren't staying current with AWS changes. I'm a couple weeks into trying to rearchitect our application and infrastructure deployments to use Terraform/Terragrunt. I noticed today that many of the terraform ECS modules ignore changes on `task_definition` changes. You commented that Terraform is not a good deployment tool for these definitions. You mentioned you are using custom tooling. Can you give any insight into how you are doing this?

**Comment by brainsik** [comment]
@mjmayer We either script around the aws CLI or write code using the AWS SDK.

Here's a link to one of the scripts we use:
https://github.com/transcom/mymove/blob/master/scripts/ecs-deploy-service-container

If you can grind through the bash, I think it gives a decent overview of how we are handling things: blue/green style deploy with rollback on failure. It should perhaps be rewritten in a real programming language. 😉 There are a bunch of scripts in there handling various ECS deployment things, but I think that's probably the best one to look at.

**Comment by mjmayer** [comment]
@brainsik Thanks for getting back to me so quickly.

Of course it is just a shell script I'm not sure what else I was expecting :-) After years of all this fancy AWS stuff, CI/CD still boils down to shell scripts to hold everything together.

I was looking into using AWS codedeploy, since it can integrate with our CI/CD (Atlassian Bamboo). After reviewing your script, I'm gonna implement your script in our environment. It provides some great feedback in stdout, so in the event there is a failure, I don't have to hunt through logs.

Thanks again!
