### ISSUE TITLE
Please create release 3.3.1

### ISSUE THREAD

**Issue by soleares** [trussworks/terraform-aws-ecs-service#192]
The 3.3.0 release had a bug and wasn't usable with TF12, AWS 3.X. [This PR](https://github.com/trussworks/terraform-aws-ecs-service/pull/171) fixed it, but it's not tagged yet so it's not easily usable. Could you please tag/release [commit b6106f9](https://github.com/trussworks/terraform-aws-ecs-service/commits/b6106f9) `terraform012` branch as release 3.3.1?

**Comment by dynamike** [comment]
Done. Thanks for the report. 

https://github.com/trussworks/terraform-aws-ecs-service/releases/tag/v3.3.1
