### ISSUE TITLE
service_registries variable is requiring optional parameters

### ISSUE THREAD

**Issue by Nava-JoshLong** [trussworks/terraform-aws-ecs-service#342]
**Describe the bug**

The `service_registries` variable has [4 parameters, and all 4 required from this module](https://github.com/trussworks/terraform-aws-ecs-service/blob/main/variables.tf#L226-L235). In the underlying module that this calls, the only required parameter is `registry_arn`, they rest are listed as optional. When we try to add this functionality on an existing module, we have to specify all 4 parameters, or the module will fail validations. However, on existing ECS services, we do not need the `port` and `container_port`, because they are optional and dealt with by the ECS config JSON. 

I think a way to fix this would to tweaking the variable structure so that it can accept those parameters not being there, and then main to set them if they are there, or null if not

**To Reproduce**
1. Create a service without the `service_registries` section defined
2. Update with adding that parameter
3. You will either get an error because parameters are not set, or because they are and you don't need them

**Expected behavior**

The parameters are optional instead of required

**Comment by rpdelaney** [comment]
Hey @Nava-JoshLong: What you're saying makes sense. If you want to send a PR, we'll set up a review. Thank you for the report!

**Comment by ahobson** [comment]
I believe this is fixed with #344

**Comment by Nava-JoshLong** [comment]
@ahobson Awesome, thanks for that!
